# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "production" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Pull submodules
      run: |
        git submodule update --init --recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore Item-Trading-App-REST-API.sln
    - name: Build
      run: dotnet build Item-Trading-App-REST-API.sln --no-restore
    - name: Unit testing the Application layer
      run: dotnet test Application.UnitTests --no-build --verbosity normal
    - name: Unit testing the Infrastructure layer
      run: dotnet test Infrastructure.UnitTests --no-build --verbosity normal
